# Generated by Django 5.2.3 on 2025-06-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa_filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('tipo_usuario', models.CharField(choices=[('GESTOR', 'Gestor'), ('FUNCIONARIO', 'Funcionário')], max_length=20, verbose_name='Tipo de Usuário')),
                ('filial_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresa_filial.filial')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
