services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gerenciapatrimonio
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gerenciapatrimonio"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_admin
      POSTGRES_DB: test_gerenciapatrimonio
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_admin -d test_gerenciapatrimonio"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
            echo 'Running migrations...' &&
            python manage.py migrate &&
            echo 'Starting server...' &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/gerenciapatrimonio
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gerenciapatrimonio
      - DB_USER=admin
      - DB_PASSWORD=admin
      - TEST_DB_HOST=db_test
      - TEST_DB_PORT=5432
      - TEST_DB_NAME=test_gerenciapatrimonio
      - TEST_DB_USER=test_admin
      - TEST_DB_PASSWORD=test_admin
      - DJANGO_SETTINGS_MODULE=configuracao.settings
      - PYTHONUNBUFFERED=1

  tests:
    build: .
    command: >
      sh -c "python /app/tests/wait-for-service.py &&
             echo 'Serviço web está pronto. Rodando suíte de testes...' &&
             pytest"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - API_HOST=web
      - DATABASE_URL=postgres://admin:admin@db:5432/gerenciapatrimonio
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gerenciapatrimonio
      - DB_USER=admin
      - DB_PASSWORD=admin
      - TEST_DB_HOST=db_test
      - TEST_DB_PORT=5432
      - TEST_DB_NAME=test_gerenciapatrimonio
      - TEST_DB_USER=test_admin
      - TEST_DB_PASSWORD=test_admin
      - DJANGO_SETTINGS_MODULE=configuracao.settings
      - PYTHONUNBUFFERED=1

  lint:
    build: .
    volumes:
      - ./src:/app
      - ./tests:/app/tests
    # Aumenta o limite de caracteres para acomodar linhas longas geradas automaticamente pelo Django
    command: flake8 . --max-line-length=95 

volumes:
  postgres_data: