# Generated by Django 5.2.3 on 2025-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=120, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
            ],
        ),
    ]
