# Generated by Django 5.2.3 on 2025-06-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaFilial', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gestores',
            field=models.ManyToManyField(related_name='empresa_administrada', through='EmpresaFilial.Gerencia', to='Usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='gerencia',
            unique_together={('usuario', 'empresa')},
        ),
    ]
