# Generated by Django 5.2.3 on 2025-06-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaFilial', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
    ]
