# Generated by Django 5.2.3 on 2025-06-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaFilial', '0003_alter_empresa_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together={('logradouro', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'cep')},
        ),
    ]
