# Generated by Django 5.2.4 on 2025-07-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa_filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(default=1)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa_filial.endereco', verbose_name='Endereço')),
                ('filial_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associado', to='empresa_filial.filial')),
            ],
            options={
                'verbose_name': 'Imobiliario',
                'verbose_name_plural': 'Imobiliarios',
            },
        ),
        migrations.CreateModel(
            name='Utilitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('funcao', models.CharField(max_length=20, verbose_name='Função')),
                ('filial_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associado', to='empresa_filial.filial')),
            ],
            options={
                'verbose_name': 'Utilitario',
                'verbose_name_plural': 'Utilitarios',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('modelo', models.CharField(max_length=25, verbose_name='Modelo')),
                ('fabricante', models.CharField(max_length=25, verbose_name='Fabricante')),
                ('filial_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associado', to='empresa_filial.filial')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
    ]
