# Generated by Django 5.2.3 on 2025-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imobiliario',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
