# Generated by Django 5.2.3 on 2025-06-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliario',
            options={'verbose_name': 'Imobiliario', 'verbose_name_plural': 'Imobiliarios'},
        ),
        migrations.AlterModelOptions(
            name='utilitario',
            options={'verbose_name': 'Utilitario', 'verbose_name_plural': 'Utilitarios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
    ]
