# Generated by Django 5.2.3 on 2025-06-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=120, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento (Opcional)')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número (Opcional)')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'unique_together': {('logradouro', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'cep')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa_filial.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('empresa_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='empresa_filial.empresa')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa_filial.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa_filial.empresa')),
            ],
        ),
    ]
