# Generated by Django 5.2.3 on 2025-06-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa_filial', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gestores',
            field=models.ManyToManyField(related_name='empresa_administrada', through='empresa_filial.Gerencia', to='usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='gerencia',
            unique_together={('usuario', 'empresa')},
        ),
    ]
