# Generated by Django 5.2.4 on 2025-07-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_filial', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together=set(),
        ),
    ]
