name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_validate_app:
    name: Rodar Suíte de Testes e Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Rodar testes com Docker Compose
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: "True"
        ALLOWED_HOSTS: "localhost,127.0.0.1,web"
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        DB_HOST: db 
        DB_PORT: 5432
        DB_NAME: ${{ secrets.POSTGRES_DB }}
        DB_USER: ${{ secrets.POSTGRES_USER }}
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: docker compose up --build --abort-on-container-exit --exit-code-from tests

    - name: Parar e remover contêineres após a execução
      if: always()
      run: docker compose down -v --remove-orphans