name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_validate_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Construir imagens Docker
      run: docker compose build

    - name: Rodar testes com Docker Compose
      run: docker compose run --rm tests 

    - name: Verificar inicialização da aplicação web
      if: success()
      run: |
        echo "Iniciando o serviço 'db'"
        docker compose up -d db 
        echo "Verificando se o serviço 'web' pode aplicar migrações e passar no system check..."
        docker compose run --rm web \ 
          sh -c "echo 'Esperando pelo serviço db na porta 5432...' && \
                 while ! nc -z db 5432; do sleep 1; done && \
                 echo 'Serviço db está pronto.' && \
                 echo 'Aplicando migrações no banco de dados principal...' && \
                 python /app/manage.py migrate && \
                 echo 'Executando Django system check (--deploy)...' && \
                 python /app/manage.py check --deploy"

    - name: Parar e remover contêineres, redes e volumes
      if: always()
      run: docker compose down -v --remove-orphans 