name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_validate_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Construir imagens Docker
      run: docker compose build

    - name: Rodar testes com Docker Compose
      run: docker compose run --rm tests 

    - name: Iniciar aplicação web e verificar estabilidade inicial
      if: success()
      run: |
        echo "Iniciando os serviços 'db' e 'web'..."
        docker compose up -d web 
        WAIT_SECONDS=30 
        echo "Aguardando ${WAIT_SECONDS} segundos para a aplicação web iniciar e estabilizar..."
        sleep $WAIT_SECONDS
        echo "Verificando o status do contêiner 'web'..."
        if ! docker compose ps web | grep -q -E "Up|running"; then
          echo "ERRO: Serviço web não está rodando ou saiu inesperadamente após ${WAIT_SECONDS} segundos."
          echo "Logs do serviço web:"
          docker compose logs web
          echo "Status dos containers:"
          docker compose ps
          exit 1
        fi
        echo "Aplicação web iniciada com sucesso e permaneceu rodando."

    - name: Parar e remover contêineres, redes e volumes
      if: always()
      run: docker compose down -v --remove-orphans 